spring.datasource.url=jdbc:postgresql://bus-tracking-db.cns8oemiwvv3.eu-north-1.rdspring.datasource.url=jdbc:postgresql://bus-tracking-db.cns8oemiwvv3.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=skkabaddi63

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=20000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.max-http-request-header-size=2MB

spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.no-cache=true

server.tomcat.keep-alive-timeout=60000
server.tomcat.max-keep-alive-requests=1000
server.tomcat.connection-timeout=60000